CREATE TABLE `power_sources` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(128) NOT NULL,
	`ps_type` enum('rectifier','inverter','ups','grid','generator','other') NOT NULL DEFAULT 'rectifier',
	`manufacturer` varchar(128),
	`model` varchar(128),
	`roomId` int,
	`location` varchar(255),
	`outputVoltage` float,
	`outputCurrentMax` float,
	`notes` text,
	`snmpEnabled` boolean NOT NULL DEFAULT false,
	`snmpHost` varchar(128),
	`snmpPort` int DEFAULT 161,
	`snmp_version` enum('v1','v2c','v3') DEFAULT 'v2c',
	`snmpCommunity` varchar(128),
	`snmpV3User` varchar(128),
	`snmpv3_auth_proto` enum('MD5','SHA'),
	`snmpV3AuthKey` varchar(255),
	`snmpv3_priv_proto` enum('DES','AES'),
	`snmpV3PrivKey` varchar(255),
	`oidOutputVoltage` varchar(128),
	`oidOutputCurrent` varchar(128),
	`oidTemperature` varchar(128),
	`oidAlarmStatus` varchar(128),
	`oidBatteryLevel` varchar(128),
	`oidLoadPercent` varchar(128),
	`snmpPollInterval` int DEFAULT 300,
	`lastPollAt` timestamp,
	`lastVoltage` float,
	`lastCurrent` float,
	`lastTemperature` float,
	`lastAlarmStatus` varchar(64),
	`lastBatteryLevel` float,
	`lastLoadPercent` float,
	`lastPollError` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `power_sources_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `power_sources` ADD CONSTRAINT `power_sources_roomId_rooms_id_fk` FOREIGN KEY (`roomId`) REFERENCES `rooms`(`id`) ON DELETE set null ON UPDATE no action;